### ISSUE TITLE
Speed up

### ISSUE THREAD

**Issue by atiklab** [cedmax/4-letter-domains#9]
Please can you help me to speed up the process.

**Comment by cedmax** [comment]
how urgent is it? 
I can look into it, but it won't be a quick fix: I just started a new job and I don't have a huge amount of time to dedicate to it, until probably a week from now. 
If you want to play with it you can try to change this file https://github.com/cedmax/4-letter-domains/blob/master/02-DNSLookup.js from doing a sequential dns check to have some parallel ones at the same time. I noticed that with many DNS lookups at the same time or in a short window my network provider was limiting my bandwidth and that's why I went for a sequential one. I appreciate it's slow, though

**Comment by cedmax** [comment]
@atiklab I think I made it much better now, please have a go at it
